api_platform:
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
  exception_to_status:
    App\Exception\EmptyBodyException: 400
    #App\Exception\InvalidConfirmationException: 404

  # collection:
  #     pagination:
  #         enabled: false
  #         page_parameter_name: _page
  #         partial: true #better performance
